15/10/21'

diff --git a/destow/destow b/destow/destow
--- a/destow/destow
+++ b/destow/destow
@@ -39,20 +39,22 @@ while true; do
     esac
 done
 
-SUCCESS=0 
-FAILURE=0 
+declare -a SUCCESS
+declare -a FAILURE
 
 for PACKAGE in * ; do
-    if [ stow -nvt ~ $PACKAGE ]; then
-        # SUCCESS++
+    stow -nvt ~ ${PACKAGE}
+    if [ $? == 0 ]; then
+        SUCCESS+=(${PACKAGE})
         printf "${GREEN}${PROGNAME}${NC}: package [${PACKAGE}] stowed succesfully.\n"
     else
-        # FAILURE++
+        FAILURE+=(${PACKAGE})
         printf "${YELLOW}${PROGNAME}${NC}: failed to stow package [${RED}${PACKAGE}${NC}].\n"
     fi
 done
 
-# Print "X packages stowed succesfully - X packages failed: pkg1, pkg2 ..."
+printf "\n\033[1m${#SUCCESS[@]}${NC} packages stowed succesfully.\n"
+printf "\033[1m${#FAILURE[@]}${NC} packages failed to be stowed.\n"
 
 exit 0
 
